 
import demoData from './demoData';

const resumeTemplate = [
  {
    id: 1,
    type: 'heading',
    x: 230,
    y: 30,
    width: 340,
    height: 40,
    content: demoData.fullName,
    styles: {
      fontSize: '26px',
      fontWeight: 'bold',
      textAlign: 'center',
      color: '#1a1a1a',
    },
  },
  {
    id: 2,
    type: 'text',
    x: 150,
    y: 75,
    width: 500,
    height: 30,
    content: `${demoData.email} | ${demoData.phone} | ${demoData.location}`,
    styles: {
      fontSize: '13px',
      textAlign: 'center',
      color: '#333',
    },
  },
  {
    id: 3,
    type: 'heading',
    x: 50,
    y: 120,
    width: 200,
    height: 30,
    content: 'Career Objective',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  {
    id: 4,
    type: 'text',
    x: 50,
    y: 150,
    width: 680,
    height: 60,
    content: demoData.careerObjective,
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  },
  {
    id: 5,
    type: 'heading',
    x: 50,
    y: 220,
    width: 200,
    height: 30,
    content: 'Education',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  ...demoData.education.map((edu, i) => ({
    id: 6 + i,
    type: 'text',
    x: 50,
    y: 255 + i * 35,
    width: 680,
    height: 30,
    content: `${edu.degree}, ${edu.institution} (${edu.year})`,
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  })),
  {
    id: 10,
    type: 'heading',
    x: 50,
    y: 300,
    width: 200,
    height: 30,
    content: 'Experience',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  ...demoData.experience.map((exp, i) => ({
    id: 11 + i,
    type: 'text',
    x: 50,
    y: 335 + i * 85,
    width: 680,
    height: 80,
    content: `${exp.role} at ${exp.company} (${exp.duration})\n${exp.description}`,
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  })),
  {
    id: 20,
    type: 'heading',
    x: 50,
    y: 520,
    width: 200,
    height: 30,
    content: 'Projects',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  ...demoData.projects.map((proj, i) => ({
    id: 21 + i,
    type: 'text',
    x: 50,
    y: 555 + i * 60,
    width: 680,
    height: 50,
    content: `${proj.title}\n${proj.description}\n${proj.link}`,
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  })),
  {
    id: 30,
    type: 'heading',
    x: 50,
    y: 680,
    width: 200,
    height: 30,
    content: 'Skills',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  {
    id: 31,
    type: 'text',
    x: 50,
    y: 710,
    width: 680,
    height: 30,
    content: demoData.skills.join(', '),
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  },
  {
    id: 32,
    type: 'heading',
    x: 50,
    y: 750,
    width: 200,
    height: 30,
    content: 'Strengths',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  {
    id: 33,
    type: 'text',
    x: 50,
    y: 780,
    width: 680,
    height: 30,
    content: demoData.strengths.join(', '),
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  },
  {
    id: 34,
    type: 'heading',
    x: 50,
    y: 820,
    width: 200,
    height: 30,
    content: 'Certifications',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  {
    id: 35,
    type: 'text',
    x: 50,
    y: 850,
    width: 680,
    height: 30,
    content: demoData.certifications.join(', '),
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  },
  {
    id: 36,
    type: 'heading',
    x: 50,
    y: 890,
    width: 200,
    height: 30,
    content: 'Hobbies',
    styles: {
      fontSize: '16px',
      fontWeight: 'bold',
      color: '#1a1a1a',
    },
  },
  {
    id: 37,
    type: 'text',
    x: 50,
    y: 920,
    width: 680,
    height: 30,
    content: demoData.hobbies.join(', '),
    styles: {
      fontSize: '13px',
      color: '#333',
    },
  },
];

export default resumeTemplate;
